development: &defaults
  adapter: mysql2
  encoding: utf8
  database: mexchange_development
  username: root
  password: 
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: mexchange_test

production:
  <<: *defaults
  database: mexchange_production
